### ISSUE TITLE
Diskinfo mounting point

### ISSUE THREAD

**Issue by TaurnilCelebrindal** [petersulyok/diskinfo#5]
Hello,
I have a mount point problem with a USB disk that has a space in the volume name

Diskinfo returns only the first part of the volume name (should be: CLE USB)

![Capture d’écran du 2024-03-02 16-30-39](https://github.com/petersulyok/diskinfo/assets/24525765/69a01875-2a59-48ca-b915-7d2465f566ed)

![Capture d’écran du 2024-03-02 16-35-23](https://github.com/petersulyok/diskinfo/assets/24525765/2c99d007-525e-417c-b3b6-ac56721c81c1)

Thanks for your help

**Comment by petersulyok** [comment]
Hi @TaurnilCelebrindal, thanks for reporting. It seems to be a bug caused by the space character.
Could you please share the output of `fdisk -l /dev/sdb` and `df` commands when the USB drive is plugged in? 


Thanks.

**Comment by petersulyok** [comment]
Hi @TaurnilCelebrindal, I think I fixed your problems. Please test it and give a feedback.

In your report you faced two independent issues:
- partition label was display incorrectly because of encoding issues raised by the `É` character
- mounting point was displayed incorrectly because of a parsing error raised by the space character

Both of the problems have been corrected in release [v3.1.0](https://github.com/petersulyok/diskinfo/releases/tag/v3.1.0), please take a look.

**Comment by TaurnilCelebrindal** [comment]
Thanks for your answer and action  ;)
